[profile.default]
src = 'blockchain/contracts'
test = 'blockchain/test'
out = 'out'
libs = ['lib']
optimizer = true
optimizer_runs = 200
solc_version = "0.8.20"
evm_version = "paris"
remappings = ["@openzeppelin/=node_modules/@openzeppelin/"]

[rpc_endpoints]
base = "https://mainnet.base.org"
base_goerli = "https://goerli.base.org"
ethereum = "https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
polygon = "https://polygon-rpc.com"
arbitrum = "https://arb1.arbitrum.io/rpc"
optimism = "https://mainnet.optimism.io"
monad = "https://rpc.monad.xyz" # Example Monad RPC URL (replace with actual)
monadTestnet = "https://testnet-rpc.monad.xyz" # Example Monad Testnet RPC URL (replace with actual)

[etherscan]
base = { key = "${BASESCAN_API_KEY}", chain = 8453, url = "https://api.basescan.org/api" }
base_goerli = { key = "${BASESCAN_API_KEY}", chain = 84531, url = "https://api-goerli.basescan.org/api" }
ethereum = { key = "${ETHERSCAN_API_KEY}" }
polygon = { key = "${POLYGONSCAN_API_KEY}" }
arbitrum = { key = "${ARBISCAN_API_KEY}" }
optimism = { key = "${OPTIMISTIC_ETHERSCAN_API_KEY}" }
monad = { key = "${MONADSCAN_API_KEY}", chain = 12345, url = "https://api.monadscan.xyz/api" } # Example Monadscan (replace with actual chain ID and URL)
monadTestnet = { key = "${MONADSCAN_API_KEY}", chain = 54321, url = "https://api.testnet.monadscan.xyz/api" } # Example Monad Testnetscan (replace with actual chain ID and URL)

[profile.default.wallets]
deployer = { keystore = "keystore/DeeksDeployer.json" }
